### ISSUE TITLE
not too bad but just want to bring attention to it

### ISSUE THREAD

**Issue by J3inx** [SenpaiHunters/SpotOn#9]
**Describe the bug**
the explicit content symbol has two e's partially overlayed over each other

**To Reproduce**
just look at a explicit content symbol on a song

**Expected behavior**
expected there to be only one e but other than that not much

**Screenshots**
<img width="233" alt="Screen Shot 2023-03-23 at 2 45 30 PM" src="https://user-images.githubusercontent.com/125412609/227317032-3427354e-c48c-4347-9dde-623a8da5d7c7.png">

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser Chrome
 - Version Chrome version 110.0.5481.178

**Additional context**

**Comment by SenpaiHunters** [comment]
Thank you for brining that to my attention it's just text shadow, this has will be fixed in the newest update, in the mean time add this line below (should be lines 133 or so... just look for site-wide text shadow)
```
"/* Site-wide text shadow */",
    " #main { ",
	"    text-shadow: 2px -1px 0px #333 !important;",
    " } ",
```
↓ that line will tell the CSS to ignore the explicit 'e' from having a shadow:
```
" .kpGMQq1KFz620g_BD_dS {", 
" text-shadow: 0px 0px 0px #333 !important",
" } ",
```
If you have nay questions feel free to ask! Again, if it doesn't work just add another comment!

**Comment by J3inx** [comment]
great that fixed it! thank you!
